//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorld {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlInputText HTMLTextField;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl HTMLHelloLabel;
		
		protected System.Web.UI.HtmlControls.HtmlButton HTMLButton;
		
		protected System.Web.UI.WebControls.TextBox NETTextField;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl NETHelloLabel;
		
		protected System.Web.UI.WebControls.Button NETButton;
	}
}
